-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
	general = {
		col = {
			active_border = "rgba(51443a77)",
			inactive_border = "rgba(221a1433)",
		},
	},
})

hl.config({
	misc = {
		background_color = "rgba(19120cFF)",
	},
})

hl.window_rule({
	name = "border_color_rgba_fe",
	match = {
		pin = 1,
	},
	-- TODO: review rule: "border_color rgba(feb877AA) rgba(feb87777)"
})
